name: Publish Package

on:
  push:
    branches:
      - "main"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
          always-auth: true
      - run: npm ci
      - run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: akhilmhdh/contributors-readme-action@v2.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
